# Generated by Django 5.0.7 on 2024-08-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0005_remove_player_user_profile_player_birthdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='preferred_foot',
        ),
        migrations.AddField(
            model_name='player',
            name='dominant_foot',
            field=models.CharField(default='Right', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='looking_for_team',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('team', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('team', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
