# Generated by Django 5.0.7 on 2024-09-02 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0009_userprofile_favorites_userprofile_followers_favorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='PlayerProfile',
        ),
    ]
