# Generated by Django 5.0.7 on 2024-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0010_rename_player_playerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='dominant_foot',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='preferred_foot',
            field=models.CharField(choices=[('left', 'Bal'), ('right', 'Jobb'), ('two', 'Kétlábas')], default='right', max_length=10, verbose_name='Milyen lábas'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='birthdate',
            field=models.DateField(verbose_name='Születési idő'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Tapasztalatok'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.IntegerField(verbose_name='Magasság'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Tartózkodási hely'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='looking_for_team',
            field=models.BooleanField(default=False, verbose_name='Keres csapatot?'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Pozíció'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='team',
            field=models.CharField(max_length=255, verbose_name='Csapatnév'),
        ),
    ]
