# Generated by Django 5.0.7 on 2024-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0015_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, to='FTapp.userprofile'),
        ),
    ]
