# Generated by Django 5.0.7 on 2024-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0017_alter_playerprofile_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
