# Generated by Django 5.0.7 on 2024-09-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0021_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='birthdate',
            field=models.DateField(verbose_name='Születési idő'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='birthdate',
            field=models.DateField(verbose_name='Születési idő'),
        ),
    ]
