# Generated by Django 5.0.7 on 2024-09-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0024_remove_message_receiver_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
