# Generated by Django 5.0.7 on 2024-09-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0031_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='experience_list',
            field=models.ManyToManyField(blank=True, related_name='player_profiles', to='FTapp.experience', verbose_name='Tapasztalatok'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='player_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTapp.playerprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FTapp.userprofile'),
        ),
    ]
