# Generated by Django 5.0.7 on 2024-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0040_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
