# Generated by Django 5.0.7 on 2024-09-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0044_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
