# Generated by Django 5.0.7 on 2024-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0045_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.TextField(verbose_name='Pozíciók'),
        ),
    ]
