# Generated by Django 5.0.7 on 2024-09-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0048_remove_coach_avatar_remove_manager_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
    ]
