# Generated by Django 5.0.7 on 2024-09-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0049_remove_userprofile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='coach',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
