# Generated by Django 5.0.7 on 2024-09-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0050_remove_coach_qualifications_coach_qualifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
