# Generated by Django 5.0.7 on 2024-09-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0053_userprofile_followers_userprofile_following_follow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='team',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='experience',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coached_team', to='FTapp.coach')),
                ('players', models.ManyToManyField(related_name='teams', to='FTapp.playerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
