# Generated by Django 5.0.7 on 2024-09-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0054_rename_team_coach_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='FTapp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coached_team', to='FTapp.coach'),
        ),
    ]
