# Generated by Django 5.0.7 on 2024-09-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0056_rename_team_coach_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profiles', to='FTapp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coached_team', to='FTapp.coach'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(null=True, related_name='teams', to='FTapp.playerprofile'),
        ),
    ]
