# Generated by Django 5.0.7 on 2024-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0057_alter_playerprofile_team_alter_team_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='FTapp.playerprofile'),
        ),
    ]
