# Generated by Django 5.0.7 on 2024-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0058_alter_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='team',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='team_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Csapatnév'),
        ),
    ]
