# Generated by Django 5.0.7 on 2024-09-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0059_remove_playerprofile_team_playerprofile_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Csapatnév'),
        ),
    ]
