# Generated by Django 5.0.7 on 2024-09-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0060_alter_playerprofile_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Csapatnév'),
        ),
    ]
