# Generated by Django 5.0.7 on 2024-09-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0061_alter_coach_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_profile', to='FTapp.team'),
        ),
    ]
