# Generated by Django 5.0.7 on 2024-09-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0062_remove_coach_team_name_coach_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_team', to='FTapp.coach'),
        ),
    ]
