# Generated by Django 5.0.7 on 2024-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0063_alter_team_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('coaches', 'Coaches'), ('players', 'Players'), ('managers', 'Managers'), ('team', 'My Team')], default='everyone', max_length=10),
        ),
    ]
