# Generated by Django 5.0.7 on 2024-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0064_post_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='FTapp.playerprofile'),
        ),
    ]
