# Generated by Django 5.0.7 on 2024-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0065_manager_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='players',
            field=models.ManyToManyField(blank=True, to='FTapp.playerprofile'),
        ),
    ]
