# Generated by Django 5.0.7 on 2024-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0066_alter_manager_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
