# Generated by Django 5.0.7 on 2024-09-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0067_alter_manager_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='managers', to='FTapp.playerprofile'),
        ),
    ]
