# Generated by Django 5.0.7 on 2024-09-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0069_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='post',
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FTapp.playerprofile'),
        ),
    ]
