# Generated by Django 5.0.7 on 2024-10-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTapp', '0076_remove_note_user_note_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FTapp.team'),
        ),
    ]
